---
driver:
  name: docker
  privileged: true
  use_sudo: false

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_diff: true

  roles_path: ../ansible-mysql-hardening/
  playbook: default.yml
  requirements_path: requirements.yml
  sudo_command: 'sudo -E -H'

platforms:
- name: centos6-ansible-latest
  driver:
    image: rndmh3ro/docker-centos6-ansible:latest
    platform: centos
- name: centos7-ansible-latest
  driver:
    image: rndmh3ro/docker-centos7-ansible:latest
    platform: centos
- name: oracle6-ansible-latest
  driver:
    image: rndmh3ro/docker-oracle6-ansible:latest
    platform: centos
- name: oracle7-ansible-latest
  driver:
    image: rndmh3ro/docker-oracle7-ansible:latest
    platform: centos
    run_command: /sbin/init
    provision_command:
      - systemctl enable ssh.service
- name: ubuntu1604-ansible-latest
  driver:
    image: rndmh3ro/docker-ubuntu1604-ansible:latest
    platform: ubuntu
    run_command: /sbin/init
- name: ubuntu1804-ansible-latest
  driver:
    image: rndmh3ro/docker-ubuntu1804-ansible:latest
    platform: ubuntu
- name: debian9-ansible-latest
  driver:
    image: rndmh3ro/docker-debian9-ansible:latest
    platform: debian
    run_command: /sbin/init
    provision_command:
      - apt install -y systemd-sysv
      - systemctl enable ssh.service
- name: debian10-ansible-latest
  driver:
    image: rndmh3ro/docker-debian10-ansible:latest
    platform: debian
    run_command: /sbin/init
    provision_command:
      - apt install -y systemd-sysv
      - systemctl enable ssh.service
- name: amazon-ansible-latest
  driver:
    image: rndmh3ro/docker-amazon-ansible:latest
    platform: centos
    run_command: /sbin/init
#- name: amazon-ansible-latest
#  driver:
#    image: rndmh3ro/docker-amazon-ansible:latest
#    platform: centos
#    run_command: /sbin/init
#    provision_command:
#      - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
#      - systemctl enable sshd.service

verifier:
  name: inspec
  sudo: true
  inspec_tests:
     - ../mysql-baseline
#    - https://github.com/dev-sec/mysql-baseline

suites:
- name: mysql
